# Directory where fastq files are stored
rna_fastqdir: {{ rna_fastqdir }}
atac_fastqdir: {{ atac_fastqdir }}

# Sample name of fastq file (only for platform of "10x-genomics", for example,
# If there is a file named pbmc_granulocyte_sorted_3k_S1_L004_R2_001.fastq.gz, the prefix is 'pbmc_granulocyte_sorted_3k'. )
rna_fastqprefix: {{ rna_fastqprefix }}
atac_fastqprefix: {{ atac_fastqprefix }}

# Species to use [GRCh38, GRCm38] (GRCh38 for human and GRCm38 for mouse)
species: {{ species }}

# The prefix of output files. DEFAULT: MAESTRO.
outprefix: {{ outprefix }}

# Number of cores to use.
cores: {{ cores }}

# Whether or not to run RSeQC for RNA sequencing. [True, False]
# If it's set to True, the pipeline will include the RSeQC part and then takes a longer time.
# By default, the pipeline will skip the RSeQC part. DEFAULT: False.
rseqc: {{ rseqc }}

# Whether or not to provide custom peaks. [False, True]
# If custompeaks is set as True, users need to provide the file location of peak file through custompeaksloc 
# and then MAESTRO will merge the custom peak file and the peak file called from all fragments using MACS2. 
# By default (False), the pipeline will use the peaks called using MACS2. DEFAULT: False.
custompeaks: {{ custompeaks }}

# IF custompeaks = TRUE, provide the file location of custom peaks
# The peak file is BED formatted with tab seperated. 
# The first column is chromsome, the second is chromStart, and the third is chromEnd.
custompeaksloc: {{ custompeaksloc }}

# Whether or not to call peaks from short fragments (shorter than 150bp). [True, False]
# If it's set as True, MAESTRO will merge the peaks called from all fragments and those called from short fragments, 
# and then use the merged peak file for further analysis.
# If not (by default), the pipeline will only use peaks called from all fragments.
shortpeaks: {{ shortpeaks }}

# Whether or not to call peaks by cluster [True, False]
# If it's set True, MAESTRO will split the bam file according to clustering result, and then call peaks for each cluster.
# By default (not set), MAESTRO will skip this step.
clusterpeaks : {{ clusterpeaks }}

# The RP model to use to calaculate gene score for scATAC-seq. [Simple, Enhanced]
# For each gene, simple model sums over the impact of all regulatory elements within the up/dowm-stream of TSS. 
# On the basis of simple model, enhanced model gives the regulatory elements within the exon region a higher weight, 
# and also excludes the regulatory elements overlapped with another gene (the promoter and exon of a nearby gene). 
# See the MAESTRO paper for more details. DEFAULT: Enhanced.
rpmodel: {{ rpmodel }}

# Gene score decay distance, could be optional from 1kb (promoter-based regulation) and 10kb(enhancer-based regulation), default is 10kb
genedistance: {{ genedistance }}

# Whether or not to perform cell-type annotation for scATAC-seq.
# By default (not set), MAESTRO will skip the step of cell-type annotation. 
# If set, please specify the method of cell-type annotation through method.
annotation: {{ annotation }}

# Method to annotate cell types for scATAC-seq [RP-based, peak-based, both]. 
# MAESTRO provides two strategies to annotate cell types for scATAC-seq data. 
# Users can choose from 'RP-based' and 'peak-based', or choose to run both of them. 
# One is based on gene regulatory potential predicted by RP model. Another is based on the bulk chromatin accessibility data from Cistrome database. 
# If 'RP-based' is set, MAESTRO performs the cell-type annotation using the gene regulatory potential to represent gene expression, 
# and the logFC of gene regulatory potential between one cluster and all the other cells is used to calculate the gene signature scores. 
# If 'peak-based' is set, MAESTRO utilizes GIGGLE to evaluate the enrichment of bulk chromatin accessibility peaks on cluster-specific peaks from scATAC-seq data, 
# and then transfers the Cistrome cluster identity from the most enriched bulk chromatin accessibility data as the cell-type annotation for the scATAC-seq cluster. 
# See the MAESTRO paper for more details. DEFAULT: RP-based.
method: {{ method }}

# Cell signature file used to annotate cell types. MAESTRO provides several sets of built-in cell signatures.
# Users can choose from ['human.immune.CIBERSORT', 'mouse.brain.ALLEN', 'mouse.all.facs.TabulaMuris', 'mouse.all.droplet.TabulaMuris'].
# Custom cell signatures are also supported. In this situation, users need to provide the file location of cell signatures,
# and the signature file is tab-seperated without header. The first column is cell type, and the second column is signature gene.
signature: {{ signature }}

# Path of the giggle annotation file required for regulator identification. 
# Please download the annotation file from http://cistrome.org/~chenfei/MAESTRO/giggle.tar.gz and decompress it.
giggleannotation: {{ giggleannotation }}

# Path to the LISA data files
lisadir: {{ lisadir }}


# Cutoff for quality control
cutoff:
  ### RNA
  # Cutoff for the number of count in each cell. DEFAULT: 1000.
  rna_count: {{ rna_count }}
  # Cutoff for the number of genes included in each cell. DEFAULT: 500.
  rna_gene: {{ rna_gene }}
  # Cutoff for the number of cells covered by each gene. DEFAULT: 10.
  rna_cell: {{ rna_cell }}
  ### ATAC
  # Minimum number of peaks included in each cell. DEFAULT: 100.
  atac_peak: {{ atac_peak }}
  # Cutoff for the number of count in each cell. DEFAULT: 1000.
  atac_count: {{ atac_count }}
  # Cutoff for fraction of reads in promoter in each cell. DEFAULT: 0.2.
  atac_frip: {{ atac_frip }}
  # Minimum number of cells covered by each peak. DEFAULT: 10.
  atac_cell: {{ atac_cell }}

# Reference genome
genome:
  # Genome index directory for STAR. Users can just download the index file
  # from http://cistrome.org/~chenfei/MAESTRO/Refdata_scRNA_MAESTRO_GRCh38_1.1.0.tar.gz and decompress it.
  # Then specify the index directory for STAR, for example, 'Refdata_scRNA_MAESTRO_GRCh38_1.1.0/GRCh38_STAR_2.7.3a'.
  rna_mapindex: {{ rna_mapindex }}
  # Genome fasta file for minimap2. Users can just download the fasta file 
  # from http://cistrome.org/~chenfei/MAESTRO/Refdata_scATAC_MAESTRO_GRCh38_1.1.0.tar.gz and decompress it. 
  # For example, 'Refdata_scATAC_MAESTRO_GRCh38_1.1.0/GRCh38_genome.fa'.
  atac_fasta: {{ atac_fasta }}


# Information about barcode (for platform of 'Dropseq' or '10x-genomics')
barcode:
  # If the platform is 'Dropseq' or '10x-genomics', please specify the barcode library (whitelist)
  # so that STARsolo can do the error correction and demultiplexing of cell barcodes.
  # The 10X Chromium whitelist file can be found inside the CellRanger distribution.
  # Please make sure that the whitelist is compatible with the specific version of the 10X chemistry: V2 or V3.
  # For example, in CellRanger 3.1.0, the V2 whitelist is 'cellranger-3.1.0/cellranger-cs/3.1.0/lib/python/cellranger/barcodes/737K-august-2016.txt'.
  # The V3 whitelist is 'cellranger-3.1.0/cellranger-cs/3.1.0/lib/python/cellranger/barcodes/3M-february-2018.txt'.
  rna_whitelist: {{ rna_whitelist }}
  atac_whitelist: {{ atac_whitelist }}

